apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: 01-baseline-bg
spec:
  replicas: 10
  strategy:
    blueGreen:
      previewService: argo-rollouts-preview-service 
      activeService: argo-rollouts-stable-service 
      autoPromotionEnabled: false
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cost-demo
  template:
    metadata:
      labels:
        app: cost-demo
    spec:
      containers:
        - name: cost-demo
          image: ghcr.io/kostis-codefresh/rollouts-autoscaling-example:v1
          # image: ghcr.io/kostis-codefresh/rollouts-autoscaling-example:v2              
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
