apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: 08-decoupled-canary
spec:
  replicas: 10
  strategy:
    canary:
      canaryService: rollout-canary-preview 
      stableService: rollout-canary-stable  
      trafficRouting:
        traefik:
          weightedTraefikServiceName: traefik-service        
      steps:
        - setWeight: 20
        - setCanaryScale: 
            replicas: 1
        - pause: {}
        - setWeight: 50
        - setCanaryScale: 
            replicas: 3
        - pause: {}
        - setWeight: 90
        - setCanaryScale: 
            replicas: 5
        - pause: {}
        - setWeight: 100
        - setCanaryScale:        
            replicas: 8
        - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cost-demo
  template:
    metadata:
      labels:
        app: cost-demo
    spec:
      containers:
        - name: cost-demo
          image: ghcr.io/kostis-codefresh/rollouts-autoscaling-example:v1
          # image: ghcr.io/kostis-codefresh/rollouts-autoscaling-example:v2             
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
