apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: 03-hpa-bg
spec:
  strategy:
    blueGreen:
      previewService: argo-rollouts-preview-service 
      activeService: argo-rollouts-stable-service 
      autoPromotionEnabled: false
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cost-demo
  template:
    metadata:
      labels:
        app: cost-demo
    spec:
      containers:
        - name: cost-demo
          image: kostiscodefresh/summer-of-k8s-app:v1
          # image: kostiscodefresh/summer-of-k8s-app:v2
          # image: kostiscodefresh/summer-of-k8s-app:v3           
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 32Mi              
