apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-preview-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cost-demo