apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: 03-as-bg-hpa
  labels:
    app: baseline-demo
spec:
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: 03-as-bg