apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: 05-baseline-canary
spec:
  replicas: 10
  strategy:
    canary:
      canaryService: argo-rollouts-canary-service 
      stableService: argo-rollouts-stable-service 
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 70
        - pause: {}
        - setWeight: 100
        - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cost-demo
  template:
    metadata:
      labels:
        app: cost-demo
    spec:
      containers:
        - name: cost-demo
          image: kostiscodefresh/summer-of-k8s-app:v1
          # image: kostiscodefresh/summer-of-k8s-app:v2
          # image: kostiscodefresh/summer-of-k8s-app:v3           
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
