apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: 09-hpa-canary
spec:
  strategy:
    canary:
      canaryService: rollout-canary-preview 
      stableService: rollout-canary-stable  
      trafficRouting:
        traefik:
          weightedTraefikServiceName: traefik-service       
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 70
        - pause: {}
        - setWeight: 100
        - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cost-demo
  template:
    metadata:
      labels:
        app: cost-demo
    spec:
      containers:
        - name: cost-demo
          image: ghcr.io/kostis-codefresh/rollouts-autoscaling-example:latest
          # image: kostiscodefresh/summer-of-k8s-app:v2
          # image: kostiscodefresh/summer-of-k8s-app:v3           
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 32Mi  