apiVersion: v1
kind: Service
metadata:
  name: rollout-canary-stable
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cost-demo